version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
  app:
    build: .
    volumes:
      - .:/bitrise/src
    command: gin --immediate --appPort=3003
    ports:
      - '3003:3003'
    links:
      - db:postgres
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_NAME: addons_ship_dev
      TEST_DB_NAME: addons_ship_test
      DB_USER: postgres
      DB_PWD: postgres
      DB_SSL_MODE: disable
      AWS_BUCKET: $AWS_BUCKET
      AWS_REGION: $AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
<<<<<<< HEAD
      ADDON_ACCESS_TOKEN: development-token
      ADDON_HOST_URL: localhost:3003
=======
>>>>>>> 40500ae7f5b6529cfc6f2d27b9131b96302e2c0f
      BITRISE_DEN_SERVER_ADMIN_SECRET_HEADER_KEY: $BITRISE_DEN_SERVER_ADMIN_SECRET_HEADER_KEY
      BITRISE_DEN_SERVER_ADMIN_SECRET: $BITRISE_DEN_SERVER_ADMIN_SECRET
      BITRISE_API_ROOT_URL: $BITRISE_API_ROOT_URL
