version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  app:
    build: .
    volumes:
      - .:/src
    command: gin --immediate --appPort=3003
    ports:
      - "3003:3003"
    links:
      - db:postgres
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_NAME: addons_ship_dev
      TEST_DB_NAME: addons_ship_test
      DB_USER: postgres
      DB_PWD: postgres
      DB_SSL_MODE: disable
